import {renderDiscoverySummary} from './discoverySummary.js';
import {escapeHtml as e, nextAction, pendingPeople} from './workflow.js';
export function renderDashboard(participants=[], journal=[], cases=[], jobs=[], decisions=[], openPerson=()=>{}) {
 const root=document.getElementById('tab-dashboard');
 const real=participants.filter(p=>p.record_type==='FIELD');
 const pending=pendingPeople(real,journal);
 root.innerHTML=`<section class="home-intro"><p class="eyebrow">INTERNAL DISCOVERY OPERATIONS</p><h2>Find the right people. Record what you learn.</h2><p><strong>Current scope: Tomatoes · Dikko/Niger</strong></p><p>Recruit and qualify actual tomato producers and people responsible for bulk tomato purchases for retail businesses.</p><p class="muted">Start with <strong>Add Potential Participant</strong> above. Then check fit, contact and interview, and review the evidence.</p></section><section class="attention"><h2>Needs your attention</h2><p>Based on real field records. Test records are excluded.</p>${pending.length?pending.map(p=>`<button class="attention-row" data-person="${e(p.participant_ref)}"><span><strong>${e(p.full_name)}</strong><br>${e(nextAction(p,journal).text)}</span><span>${e(nextAction(p,journal).action)} →</span></button>`).join(''):'<p class="empty-state">No pending contact or qualification work in the saved field records. Add a potential participant, or open Participants to review existing evidence.</p>'}</section><section><h2>Discovery at a glance</h2><div class="dashboard-grid">${[['Potential participants',real.length],['Qualified',real.filter(p=>p.eligibility_status==='ELIGIBLE').length],['Need verification',real.filter(p=>p.eligibility_status==='PENDING_VERIFICATION').length],['Declined / outside group',real.filter(p=>p.contact_outcome==='DECLINED'||p.eligibility_status==='INELIGIBLE').length]].map(([name,n])=>`<div class="dashboard-card"><div class="card-title">${name}</div><div class="metric-big">${n}</div></div>`).join('')}</div><p class="muted">${participants.length-real.length} test records are available in Participants for practice. Qualification is not proof of demand or willingness to pay.</p></section>`;
 const details=document.createElement('details');details.className='form-section';details.innerHTML='<summary>Detailed recruitment and stage summary</summary><p class="muted">Includes practice records. Counts show saved statuses, not conversion rates or validated demand.</p><div id="discovery-summary"></div>';root.append(details);
 renderDiscoverySummary(participants,journal,cases,jobs,decisions);
 root.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>openPerson(b.dataset.person));
}
