import {CLAIMED_ROLE_LABELS} from '../domain/constants.js';
import {escapeHtml as e,label,nextAction,lastContact} from './workflow.js';
export function renderParticipantTable(participants=[],onSelectParticipant,onEditParticipant,journal=[]) {
 const root=document.getElementById('tab-registry');
 root.innerHTML=`<h2>Participants</h2><p>Find someone, check their fit, and open their contact and interview history.</p><div class="table-toolbar"><label>Search<input id="registry-search" class="form-control" type="search" placeholder="Name, reference or referral"></label><label>Status<select id="filter-eligibility" class="form-control"><option value="ALL">All</option><option value="ELIGIBLE">Qualified</option><option value="PENDING_VERIFICATION">Needs verification</option><option value="INELIGIBLE">Outside group</option><option value="DECLINED">Declined</option></select></label><label>Role<select id="filter-role" class="form-control"><option value="ALL">All roles</option><option value="PRODUCER">Producers</option><option value="RETAIL_PURCHASER">Retail purchasers / approvers</option><option value="TRADER_REFERRAL">Trader referrals</option><option value="OTHER">Other</option></select></label></div><p id="visible-count" aria-live="polite"></p><div class="table-container"><table class="data-table participant-table"><thead><tr><th>Participant</th><th>Role / area</th><th>Status</th><th>Last contact logged</th><th>Next action</th></tr></thead><tbody id="table-body-participants"></tbody></table></div>`;
 const search=root.querySelector('#registry-search'), status=root.querySelector('#filter-eligibility'), role=root.querySelector('#filter-role');
 function render(){
 const filtered=participants.filter(p=>[p.full_name,p.participant_ref,p.referral_source].join(' ').toLowerCase().includes(search.value.toLowerCase())&&(status.value==='ALL'||(status.value==='DECLINED'?p.contact_outcome==='DECLINED':p.eligibility_status===status.value))&&(role.value==='ALL'||p.claimed_role===role.value||(role.value==='RETAIL_PURCHASER'&&p.claimed_role==='RETAIL_APPROVER')));
 root.querySelector('#visible-count').textContent=`${filtered.length} of ${participants.length} people`;
 root.querySelector('tbody').innerHTML=filtered.length?filtered.map(p=>{const time=lastContact(p.participant_ref,journal);return `<tr><td data-label="Participant"><button class="text-button" data-open="${e(p.participant_ref)}">${e(p.full_name)}</button><small>${e(p.participant_ref)} · ${p.record_type==='TEST'?'Practice record':'Field record'}</small></td><td data-label="Role / area">${e(CLAIMED_ROLE_LABELS[p.claimed_role])}<small>${e(p.geography?.town)}, ${e(p.geography?.state)}</small></td><td data-label="Status"><span class="badge badge-${p.eligibility_status==='ELIGIBLE'?'eligible':p.eligibility_status==='INELIGIBLE'?'ineligible':'pending'}">${e(label(p.eligibility_status))}</span><small>${e(label(p.contact_outcome))}</small></td><td data-label="Last contact">${time?e(new Date(time).toLocaleString()):'No contact logged'}</td><td data-label="Next action"><button class="btn btn-secondary" data-open="${e(p.participant_ref)}">${e(nextAction(p,journal).action)}</button><button class="btn btn-ghost" data-edit="${e(p.participant_ref)}">Edit details</button></td></tr>`}).join(''):`<tr><td colspan="5"><div class="empty-state">${participants.length?'No matches. Clear the search or choose All statuses.':'No participants yet. Add someone who may produce tomatoes or buy tomatoes in bulk for a retail business in Dikko/Niger.'}<button class="btn btn-secondary" id="empty-add">Add Potential Participant</button></div></td></tr>`;
 root.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>onSelectParticipant(b.dataset.open));
 root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>onEditParticipant(participants.find(p=>p.participant_ref===b.dataset.edit)));
 const add=root.querySelector('#empty-add');if(add)add.onclick=()=>document.getElementById('btn-new-candidate').click();
 }
 search.oninput=render;status.onchange=render;role.onchange=render;render();
}
